// Pre-defined suggestions list for auto-complete
const SUGGESTIONS_DB = [
  "What is the weather in Ho Chi Minh City today?",
  "How do I create a new customer profile?",
  "Explain LEO CDP data architecture",
  "Show me the latest user statistics",
  "Activate the 'Summer Sale Target' segment on Facebook Page immediately",
  "Activate the 'Summer Sale Target' segment on Zalo OA immediately",
  "Generate a report on last month's user engagement",
  "How to integrate LEO CDP with Shopify?",
  "List all data sources connected to LEO CDP",
  "What are the new features in the latest LEO CDP update?",
  "Troubleshoot data sync issues",
  "How to set up automated email campaigns?",
  "Best practices for data segmentation",
  "Optimize customer journey mapping",
  "What is the average session duration for users?",
  "How to export data to CSV?",
  "Create a custom dashboard for sales metrics",
  "Check system status",
  "Who are the top active users?",
  "Integration guide for Python",
  "for segment 'new user' at channel Zalo, send 'hello @user' message",
  "for segment 'user purchased product A', send 'thank you @user' email",
];
